# Generated by scripts/gen_distribution.py in writ-agent/provio; do not edit by hand.
class Provio < Formula
  desc "Safety floor for AI coding agents: one policy, checked before every tool call"
  homepage "https://getprovio.vercel.app"
  version "0.1.5"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/writ-agent/provio/releases/download/v0.1.5/provio-aarch64-apple-darwin"
      sha256 "02e71cbc64bd4f0af2a9c90733fae6512561d73ff75c9a8c27f4234d7ac9052d"
    else
      url "https://github.com/writ-agent/provio/releases/download/v0.1.5/provio-x86_64-apple-darwin"
      sha256 "e8ccccd00743c4b53a0216ab7abae18b8eb3372a546bbf4e617a4817b6ca9e44"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/writ-agent/provio/releases/download/v0.1.5/provio-aarch64-unknown-linux-musl"
      sha256 "b3d4d8b50cae0c200cfc5d564cab56f2d60e7094541102763025008941e0f9ad"
    else
      url "https://github.com/writ-agent/provio/releases/download/v0.1.5/provio-x86_64-unknown-linux-musl"
      sha256 "9ffa29e6335ab260d3c197f7565a228d98df178136547222f946c25296974863"
    end
  end

  def install
    bin.install Dir["provio-*"].first => "provio"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/provio --version")
    (testpath/"provio.yaml").write <<~YAML
      version: 1
      default: allow
      packs: [floor]
    YAML
    system bin/"provio", "test", "cargo build"
    assert_match "floor-rm-home-or-root-denied", shell_output("#{bin}/provio test 'rm -rf ~'", 2)
  end
end
