# Generated by scripts/gen_distribution.py in writ-agent/provio; do not edit by hand.
class Provio < Formula
  desc "Safety floor for AI coding agents: one policy, checked before every tool call"
  homepage "https://getprovio.vercel.app"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/writ-agent/provio/releases/download/v0.1.3/provio-aarch64-apple-darwin"
      sha256 "49c5eff0e577328a286b523e5750e830254b9c784183bd4be0361f148579a8d9"
    else
      url "https://github.com/writ-agent/provio/releases/download/v0.1.3/provio-x86_64-apple-darwin"
      sha256 "c2f379d0fb329da5bdcfc6c6a055d8ab6aba970272e204945ddd4cbef66f82db"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/writ-agent/provio/releases/download/v0.1.3/provio-aarch64-unknown-linux-musl"
      sha256 "6c6ae8fcd8b293680088cbd276cd38f4bf587c1de622b44b7fb74b5d49c88184"
    else
      url "https://github.com/writ-agent/provio/releases/download/v0.1.3/provio-x86_64-unknown-linux-musl"
      sha256 "bae173d91756824131e6fc8e993dfad9119933c68f87cba0ea942f8b1ae8e88c"
    end
  end

  def install
    bin.install Dir["provio-*"].first => "provio"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/provio --version")
    (testpath/"provio.yaml").write <<~YAML
      version: 1
      default: allow
      packs: [floor]
    YAML
    system bin/"provio", "test", "cargo build"
    assert_match "floor-rm-home-or-root-denied", shell_output("#{bin}/provio test 'rm -rf ~'", 2)
  end
end
