# Generated by scripts/gen_distribution.py in writ-agent/provio; do not edit by hand.
class Provio < Formula
  desc "Safety floor for AI coding agents: one policy, checked before every tool call"
  homepage "https://getprovio.vercel.app"
  version "0.1.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/writ-agent/provio/releases/download/v0.1.4/provio-aarch64-apple-darwin"
      sha256 "9cbd156e95bad55d974d9a5d6ef3902065b734e69590272635ad223480e0f452"
    else
      url "https://github.com/writ-agent/provio/releases/download/v0.1.4/provio-x86_64-apple-darwin"
      sha256 "cac2d5e5611e22e703e14108cee603cb9504b1d38868a238907de3d1aa592967"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/writ-agent/provio/releases/download/v0.1.4/provio-aarch64-unknown-linux-musl"
      sha256 "bf1e26135575503d3985385b5eacab4630db8d859f8b36e9ccb06eab7df6cbf7"
    else
      url "https://github.com/writ-agent/provio/releases/download/v0.1.4/provio-x86_64-unknown-linux-musl"
      sha256 "ae6b3e5ef44d144ec605728443a9d273f184380adb909daa438dfa9e5579c58e"
    end
  end

  def install
    bin.install Dir["provio-*"].first => "provio"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/provio --version")
    (testpath/"provio.yaml").write <<~YAML
      version: 1
      default: allow
      packs: [floor]
    YAML
    system bin/"provio", "test", "cargo build"
    assert_match "floor-rm-home-or-root-denied", shell_output("#{bin}/provio test 'rm -rf ~'", 2)
  end
end
